input_name=input('enter your name :')
input_last_name=input('enter your last name :')
input_age=input('enter your age :')
input_city=input('enter your city :')
print(f'Hello:{input_name} {input_last_name}.')
print(f'Age:{input_age}.')
print(f'City:{input_city}.')
